FROM ubi8/ubi:8.3
MAINTAINER April Merritt april_merritt@anfcorp.com
LABEL description="A custom apache container based on UBI 8"
RUN yum install -y httpd && yum clean all
RUN echo "Hello from containerfile" > /var/www/html/index.html
EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
